require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecipeCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # RecipeCategory. As you add validations to RecipeCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecipeCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recipe_categories as @recipe_categories" do
      recipe_category = RecipeCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recipe_categories).should eq([recipe_category])
    end
  end

  describe "GET show" do
    it "assigns the requested recipe_category as @recipe_category" do
      recipe_category = RecipeCategory.create! valid_attributes
      get :show, {:id => recipe_category.to_param}, valid_session
      assigns(:recipe_category).should eq(recipe_category)
    end
  end

  describe "GET new" do
    it "assigns a new recipe_category as @recipe_category" do
      get :new, {}, valid_session
      assigns(:recipe_category).should be_a_new(RecipeCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested recipe_category as @recipe_category" do
      recipe_category = RecipeCategory.create! valid_attributes
      get :edit, {:id => recipe_category.to_param}, valid_session
      assigns(:recipe_category).should eq(recipe_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecipeCategory" do
        expect {
          post :create, {:recipe_category => valid_attributes}, valid_session
        }.to change(RecipeCategory, :count).by(1)
      end

      it "assigns a newly created recipe_category as @recipe_category" do
        post :create, {:recipe_category => valid_attributes}, valid_session
        assigns(:recipe_category).should be_a(RecipeCategory)
        assigns(:recipe_category).should be_persisted
      end

      it "redirects to the created recipe_category" do
        post :create, {:recipe_category => valid_attributes}, valid_session
        response.should redirect_to(RecipeCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recipe_category as @recipe_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecipeCategory.any_instance.stub(:save).and_return(false)
        post :create, {:recipe_category => {  }}, valid_session
        assigns(:recipe_category).should be_a_new(RecipeCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecipeCategory.any_instance.stub(:save).and_return(false)
        post :create, {:recipe_category => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recipe_category" do
        recipe_category = RecipeCategory.create! valid_attributes
        # Assuming there are no other recipe_categories in the database, this
        # specifies that the RecipeCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecipeCategory.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => recipe_category.to_param, :recipe_category => { "these" => "params" }}, valid_session
      end

      it "assigns the requested recipe_category as @recipe_category" do
        recipe_category = RecipeCategory.create! valid_attributes
        put :update, {:id => recipe_category.to_param, :recipe_category => valid_attributes}, valid_session
        assigns(:recipe_category).should eq(recipe_category)
      end

      it "redirects to the recipe_category" do
        recipe_category = RecipeCategory.create! valid_attributes
        put :update, {:id => recipe_category.to_param, :recipe_category => valid_attributes}, valid_session
        response.should redirect_to(recipe_category)
      end
    end

    describe "with invalid params" do
      it "assigns the recipe_category as @recipe_category" do
        recipe_category = RecipeCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecipeCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => recipe_category.to_param, :recipe_category => {  }}, valid_session
        assigns(:recipe_category).should eq(recipe_category)
      end

      it "re-renders the 'edit' template" do
        recipe_category = RecipeCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecipeCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => recipe_category.to_param, :recipe_category => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recipe_category" do
      recipe_category = RecipeCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => recipe_category.to_param}, valid_session
      }.to change(RecipeCategory, :count).by(-1)
    end

    it "redirects to the recipe_categories list" do
      recipe_category = RecipeCategory.create! valid_attributes
      delete :destroy, {:id => recipe_category.to_param}, valid_session
      response.should redirect_to(recipe_categories_url)
    end
  end

end
